/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/dingo-o/chassis-panels-dingo-o.glb');
  return (
    <group ref={group} {...props} dispose={null} position={props.modelPosition} rotation={props.modelRotation}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['chassis-panels-dingo-o'].geometry}
        material={nodes['chassis-panels-dingo-o'].material}
      >
        <meshStandardMaterial attach="material" color={props.modelColour} />
      </ mesh>
    </group>
  );
}

useGLTF.preload('/models/dingo-o/chassis-panels-dingo-o.glb');